dist: focal
language: php
php:
  - 7.4

install:
  - composer install

script:
  - composer test
  - vendor/bin/phpunit --coverage-clover coverage.xml
  - vendor/bin/infection
  - composer run-static-analysis

after_success:
  - bash <(curl -s https://codecov.io/bash)